services:
  - type: web
    name: job-portal-backend
    env: java
    region: ohio
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080

  - type: static
    name: job-portal-frontend
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    staticPublishPath: ./dist
    rootDir: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
