services:
  - type: web
    name: job-portal-backend-docker
    runtime: docker
    region: ohio
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: job-portal-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
